// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisplayInfo() {
  return window['go']['backend']['App']['DisplayInfo']();
}

export function DownloadRepo(arg1, arg2) {
  return window['go']['backend']['App']['DownloadRepo'](arg1, arg2);
}

export function DownloadRepos(arg1, arg2) {
  return window['go']['backend']['App']['DownloadRepos'](arg1, arg2);
}

export function GetClientIP() {
  return window['go']['backend']['App']['GetClientIP']();
}

export function Notify(arg1) {
  return window['go']['backend']['App']['Notify'](arg1);
}
