// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DisplayInfo():Promise<model.DisplayInfo>;

export function DownloadRepo(arg1:string,arg2:string):Promise<void>;

export function DownloadRepos(arg1:Array<string>,arg2:string):Promise<void>;

export function GetClientIP():Promise<string>;

export function Notify(arg1:model.NotifyData):Promise<void>;
