// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClientIP() {
  return window['go']['backend']['App']['GetClientIP']();
}

export function Notify(arg1) {
  return window['go']['backend']['App']['Notify'](arg1);
}
