// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetClientIP():Promise<string>;

export function Notify(arg1:model.NotifyData):Promise<void>;
