// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAuthor() {
  return window['go']['api']['DisplayConfig']['GetAuthor']();
}

export function GetGithub() {
  return window['go']['api']['DisplayConfig']['GetGithub']();
}

export function GetHost() {
  return window['go']['api']['DisplayConfig']['GetHost']();
}

export function GetTitle() {
  return window['go']['api']['DisplayConfig']['GetTitle']();
}

export function GetVersion() {
  return window['go']['api']['DisplayConfig']['GetVersion']();
}
