// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAuthor():Promise<string>;

export function GetGithub():Promise<string>;

export function GetHost():Promise<string>;

export function GetTitle():Promise<string>;

export function GetVersion():Promise<string>;
