// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Login(arg1) {
  return window['go']['api']['SchoolClient']['Login'](arg1);
}

export function Logout() {
  return window['go']['api']['SchoolClient']['Logout']();
}
