// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Login(arg1:model.UserInfo):Promise<model.SchoolLoginResp>;

export function Logout():Promise<model.SchoolLoginResp>;
