name: Build Wails App

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd frontend && yarn install

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build the Wails App with NSIS and UPX
        run: wails build

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: wails-windows-build
          path: build/bin/

  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: wails-windows-build
          path: build/bin/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.1.3
          name: Release 1.1.2
          files: build/bin/*.exe
          token: ${{ secrets.GITHUB_TOKEN }}
