name: Build Wails App

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: cd frontend && yarn config set registry https://registry.npmmirror.com && yarn

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build the Wails App with NSIS and UPX
        run: wails build

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: wails-windows-build
          path: build/bin/

  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: wails-windows-build
          path: build/bin/

      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=version::1.1.2"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          files: build/bin/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
